### ISSUE TITLE
Overview of benchmarks

### ISSUE THREAD

**Issue by adigitoleo** [seismic-anisotropy/PyDRex#147]
List of benchmarks with checkboxes to indicate if they are finalised including result assertions (for CI tests) and output visualisations (if applicable).

**CI tests**:
- [x] A-type olivine dislocation creep tests (`TestDislocationCreepOlivineA` in `test_core.py`). These check that the rotation rate for individual grains of A-type olivine matches an analytical result, for various simple shear geometries and dislocation slip on a single slip system.
- [x] Enstatite dislocation creep tests (`TestDislocationCreepOPX` in `test_core.py`). These check that the rotation rate for individual grains of enstatite matches an analytical result, for various simple shear geometries.
- [x] A-type olivine 2D recrystallisation tests (`TestRecrystallisation2D` in `test_core.py`). These check grain growth rates for A-type olivine grains in a known 2D distribution (on a circle) under simple shear. If the circle is in the deformation plane, analytical results are available for comparison (because only one slip system is active) and growth occurs for grains at both subparallel and suborthogonal orientations to the shear. If the circle is in the shear plane, multiple slip systems are active and the test instead checks that the dominant slip system changes depending on the angular distance of the grain orientation from the shear direction. Grain growth has two instead of four peaks, i.e. growth is restricted to grains oriented subparallel to the shear.  (#146)
- [x] Grain boundary migration sanity checks. These should be some quick checks to ensure that M*=0 is a reliable way to turn off recrystallisation (i.e. grain sizes don't change) and that M*>0 causes decreasing grain size medians. No need for visualisations. (#148)
- [x] Number of grains convergence test (currently `test_ngrains` in `test_simple_shear_2d.py`) and some uncommitted versions which need to be merged. This should test how many grains are generally required for stable outputs. ~~Needs to run with up to 10000 grains at least, so requires HPC resources.~~ (#150)

**Parallel tests and examples (require `pytest --runslow`)**:
- [x] Grain boundary migration validation test comparing to the Fortran 90 output (`test_dvdx_GBM` in `test_simple_shear_2d.py`). This test checks that GBM (higher M* parameter) speeds up the CPO alignment and also compares outputs to the Fortran 90 results (only above 40% strain, D-Rex results at low strain are not numerically stable or consistent in the literature). The output figure also shows the Zhang & Karato 1995 (original D-Rex calibration) experimental results.
- [x] Grain boundary sliding and nucleation efficiency ensembles (`test_dvdx_ensemble` in `test_simple_shear_2d.py`). This is a collection of 9 ensembles that each have a unique combination of GBS, GBM and nucleation parameters. It is intended to show the effects of GBS and nucleation on CPO alignment. There are no assert statements because this is a new benchmark we are introducing, so for now it is primarily qualitative.
- ~~Timestepping convergence test (currently only an uncommitted script that used the Fortran 90 code). This should test the timestep resolution generally required for stable output in some typical steady flow field. Probably the `test_corner_prescribed_init_isotropic` in `test_corner_flow_2d.py` can be converted into an ensemble that covers this, instead of using assert statements to compare arbitrary values.~~ Decided not to add this for first release, the user already has the option to change solvers and tolerances for `update_orientations`.
- [x] 2D corner flow example, qualitatively comparable to Fig. 5 in Kaminski & Ribe  2002, and also showing that the M-index is working. (#152)
- [x] Changing shear direction tests (currently uncommitted code on `3d_shear` branch). These ensembles are for comparison with Fraters & Billen Fig 5 and visualisations should have the same aspect ratio as in that paper. The tests show that A-type olivine and enstatite evolve towards CPO textures with orthogonal point maxima. They also demonstrate that we can handle 3D geometry and simple time-dependence like Fraters & Billen 2021. (#158)

It would also be nice to have a way to settle the debate about the importance and duration of transient CPO textures depending on initial conditions. Boneh et al. 2015 argue for protracted transient CPO based on experiments and models, but their experiments are in uniaxial compression geometry not simple shear and they use 1000 grains for D-Rex which is probably not enough. Also they have a different set of CRSS values for olivine and use M*=10 which does not agree with the Zhang & Karato simple shear calibration. Maybe some of the other results from the Skemer 2016 datafile can be used for some additional calibration tests. (#157)
